### PR TITLE
[fix] Fix startup failure when parallelism>1

### LINKED ISSUE #50: [Bug]
**Describe the bug**
The snowflake connector currently does not support concurrency and can only transmit on a single pod. When `Replicas>1` is set on the SN Cloud, the connector fails to start.

**To Reproduce**
1. Go to 'CREATE A SINK' and click on `snowflake`.
2. Fill in the configuration information and set `Replicas=2`.
image
3. Click on 'SUBMIT' and wait for the connector to be created.
4. The connector keeps restarting and the state is `Not Ready`.
image

**Expected behavior**
When `replicas>1`, the snowflake connector should work well.

**Environment**
 - Deployment: test env for the SN cloud
 - Connector version: 2.9.4.1

**Additional context**
This problem occurs because the Snowflake connector currently does not support multiple pods for concurrent transport. For adding the Snowflake to the SN cloud, we currently have two options. 

- Option a is to temporarily limit the `replicas=1` of the Snowflake connector in the cloud UI and release it first. 
   This is the relevant pr: https://github.com/streamnative/cloud-manager/pull/2743.

- Option b is when the snowflake connector supports concurrency. Then add Snowflake to the SN cloud.

Note: Single pod will not affect the user unless the user has special requirements for TPS. This is [the performance test report](https://github.com/streamnative/pulsar-io-snowflake/blob/master/docs/performance-test-report.md), The TPS of a single pod can reach 9k/s.

### PR DESCRIPTION
**Pull request by danpi**
Fixes #50 

### Motivation

The snowflake connector currently does not support concurrency and can only transmit on a single pod. When Replicas>1 is set, the connector fails to start. 

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

Check the box below.

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

File: src/main/java/org/apache/pulsar/ecosystem/io/snowflake/internal/SnowflakeSinkServiceV1.java [hunk 1]
```diff
@@ -479,17 +480,16 @@ private boolean resetCleanerFiles() {
 
         // If there are files already on stage, we need to decide whether we will reprocess the offsets
         // or we will purge them.
```
Comment (alpreu) [inline src/main/java/org/apache/pulsar/ecosystem/io/snowflake/internal/SnowflakeSinkServiceV1.java:482]: This comment is outdated now I think

**Review by alpreu — APPROVED** [review]
Looks good to me, maybe you can update the comments once again to make sure they are up to date

File: src/main/java/org/apache/pulsar/ecosystem/io/snowflake/internal/SnowflakeSinkServiceV1.java (hunk 1 above)
Comment (danpi) [reply src/main/java/org/apache/pulsar/ecosystem/io/snowflake/internal/SnowflakeSinkServiceV1.java]: Good suggestion, I have updated the comment.
